apiVersion: v1
kind: Pod
metadata:
  name: db-green-pod
  namespace: default
  labels:
    environment: green
    tier: db
spec:
  containers:
  - name: db-container
    image: localhost:5000/my-nginx
    ports:
    - containerPort: 80
