apiVersion: v1
kind: Pod
metadata:
  name: db-red-pod
  namespace: default
  labels:
    environment: red
    tier: db
spec:
  containers:
  - name: db-container
    image: nginx
    ports:
    - containerPort: 80
