apiVersion: v1
kind: Pod
metadata:
  name: web-green-pod
  namespace: default
  labels:
    environment: green
    tier: web
spec:
  containers:
  - name: web-container
    image: localhost:5000/my-nginx
    ports:
    - containerPort: 80
