apiVersion: v1
kind: Pod
metadata:
  name: web_red_pod
  namespace: default
  labels:
    environment: red
    tier: web
spec:
  containers:
  - name: web-container
    image: nginx
    ports:
    - containerPort: 80
